spring:
  profiles:
    active: dev

---
#开发环境配置
spring:
  profiles: dev
  application:  
    name: micro-cloud-eureka-client-user

server:
  port: 8801
busi:
  open: N


---
#生产环境配置
spring:
  profiles: prod
  application:  
    name: micro-cloud-eureka-client-user

server:
  port: 8901

busi:
  open: N
